In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.Max_columns' , None)
pd.set_option('display.Max_rows', None)

In [3]:
bk = pd.read_csv(r"C:\Users\rhuta\Downloads\Bank_customer_churn_outside.csv")

In [4]:
bk.head(10)

ID  Gender  Age Region_Code     Occupation Channel_Code  Vintage  \
0  NNVBBKZB  Female   73       RG268          Other           X3       43   
1  IDD62UNG  Female   30       RG277       Salaried           X1       32   
2  HD3DSEMC  Female   56       RG268  Self_Employed           X3       26   
3  BF3NC7KV    Male   34       RG270       Salaried           X1       19   
4  TEASRWXV  Female   30       RG282       Salaried           X1       33   
5  ACUTYTWS    Male   56       RG261  Self_Employed           X1       32   
6  ETQCZFEJ    Male   62       RG282          Other           X3       20   
7  JJNJUQMQ  Female   48       RG265  Self_Employed           X3       13   
8  ZMQFYKCB  Female   40       RG283  Self_Employed           X2       38   
9  NVKTFBA2  Female   55       RG268  Self_Employed           X2       49   

  Credit_Product  Avg_Account_Balance Is_Active  Is_Lead  
0             No              1045696        No        0  
1             No               581988        No        0  
2             No              1484315       Yes        0  
3             No               470454        No        0  
4             No               886787        No        0  
5             No               544163       Yes        0  
6            NaN              1056750       Yes        1  
7             No               444724       Yes        0  
8             No              1274284        No        0  
9            Yes              2014239        No        0

In [5]:
bk.shape

(245725, 11)

In [7]:
#bk.Region_Code.value_counts()

In [8]:
bk.isnull().sum()

ID                         0
Gender                     0
Age                        0
Region_Code                0
Occupation                 0
Channel_Code               0
Vintage                    0
Credit_Product         29325
Avg_Account_Balance        0
Is_Active                  0
Is_Lead                    0
dtype: int64

In [9]:
bk.Credit_Product.value_counts()

No     144357
Yes     72043
Name: Credit_Product, dtype: int64

In [10]:
bk = bk.drop(['ID'], axis = 1)

In [11]:
bk.shape

(245725, 10)

In [12]:
bk.Credit_Product = bk.Credit_Product.fillna('No')

In [13]:
bk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245725 entries, 0 to 245724
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype 
---  ------               --------------   ----- 
 0   Gender               245725 non-null  object
 1   Age                  245725 non-null  int64 
 2   Region_Code          245725 non-null  object
 3   Occupation           245725 non-null  object
 4   Channel_Code         245725 non-null  object
 5   Vintage              245725 non-null  int64 
 6   Credit_Product       245725 non-null  object
 7   Avg_Account_Balance  245725 non-null  int64 
 8   Is_Active            245725 non-null  object
 9   Is_Lead              245725 non-null  int64 
dtypes: int64(4), object(6)
memory usage: 18.7+ MB


In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
bk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245725 entries, 0 to 245724
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype 
---  ------               --------------   ----- 
 0   Gender               245725 non-null  object
 1   Age                  245725 non-null  int64 
 2   Region_Code          245725 non-null  object
 3   Occupation           245725 non-null  object
 4   Channel_Code         245725 non-null  object
 5   Vintage              245725 non-null  int64 
 6   Credit_Product       245725 non-null  object
 7   Avg_Account_Balance  245725 non-null  int64 
 8   Is_Active            245725 non-null  object
 9   Is_Lead              245725 non-null  int64 
dtypes: int64(4), object(6)
memory usage: 18.7+ MB


In [138]:
bk.corr()

Gender       Age  Region_Code  Occupation  \
Gender               1.000000  0.152076     0.004813    0.031536   
Age                  0.152076  1.000000     0.117914   -0.127753   
Region_Code          0.004813  0.117914     1.000000    0.012186   
Occupation           0.031536 -0.127753     0.012186    1.000000   
Channel_Code         0.150586  0.605543     0.103018    0.123937   
Vintage              0.146380  0.631242     0.118810    0.027156   
Credit_Product       0.042976  0.129865     0.048206    0.015217   
Avg_Account_Balance  0.022477  0.145232     0.076999   -0.038496   
Is_Active            0.064207  0.218770     0.059576    0.077208   
Is_Lead              0.072068  0.230814     0.062501    0.012415   

                     Channel_Code   Vintage  Credit_Product  \
Gender                   0.150586  0.146380        0.042976   
Age                      0.605543  0.631242        0.129865   
Region_Code              0.103018  0.118810        0.048206   
Occupation               0.123937  0.027156        0.015217   
Channel_Code             1.000000  0.537852        0.178149   
Vintage                  0.537852  1.000000        0.095078   
Credit_Product           0.178149  0.095078        1.000000   
Avg_Account_Balance      0.099911  0.167433        0.046030   
Is_Active                0.249655  0.209356       -0.110699   
Is_Lead                  0.261211  0.279642        0.117709   

                     Avg_Account_Balance  Is_Active   Is_Lead  
Gender                          0.022477   0.064207  0.072068  
Age                             0.145232   0.218770  0.230814  
Region_Code                     0.076999   0.059576  0.062501  
Occupation                     -0.038496   0.077208  0.012415  
Channel_Code                    0.099911   0.249655  0.261211  
Vintage                         0.167433   0.209356  0.279642  
Credit_Product                  0.046030  -0.110699  0.117709  
Avg_Account_Balance             1.000000   0.076637  0.053370  
Is_Active                       0.076637   1.000000  0.085723  
Is_Lead                         0.053370   0.085723  1.000000

In [17]:
le = LabelEncoder()

In [19]:
bk[bk.select_dtypes(include = ['object']).columns] = bk[bk.select_dtypes(include = ['object']).columns].apply(le.fit_transform)

In [20]:
bk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245725 entries, 0 to 245724
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Gender               245725 non-null  int32
 1   Age                  245725 non-null  int64
 2   Region_Code          245725 non-null  int32
 3   Occupation           245725 non-null  int32
 4   Channel_Code         245725 non-null  int32
 5   Vintage              245725 non-null  int64
 6   Credit_Product       245725 non-null  int32
 7   Avg_Account_Balance  245725 non-null  int64
 8   Is_Active            245725 non-null  int32
 9   Is_Lead              245725 non-null  int64
dtypes: int32(6), int64(4)
memory usage: 13.1 MB


In [21]:
bk.head()

Gender  Age  Region_Code  Occupation  Channel_Code  Vintage  \
0       0   73           18           1             2       43   
1       0   30           27           2             0       32   
2       0   56           18           3             2       26   
3       1   34           20           2             0       19   
4       0   30           32           2             0       33   

   Credit_Product  Avg_Account_Balance  Is_Active  Is_Lead  
0               0              1045696          0        0  
1               0               581988          0        0  
2               0              1484315          1        0  
3               0               470454          0        0  
4               0               886787          0        0

In [118]:
#Sampling
from sklearn.model_selection import train_test_split

In [119]:
bk_train , bk_test = train_test_split(bk, test_size = 0.2)

In [120]:
bk_train_x = bk_train.iloc[ : , 0:-1]
bk_train_y = bk_train.iloc[ : , -1]

In [121]:
bk_test_x = bk_test.iloc[ : , 0:-1]
bk_test_y = bk_test.iloc[ : , -1]

In [122]:
bk_train_x.shape

(196580, 9)

In [123]:
from sklearn.linear_model import LogisticRegression

In [124]:
log_bk  = LogisticRegression()

In [125]:
log_bk.fit(bk_train_x, bk_train_y)

LogisticRegression()

In [126]:
pred = log_bk.predict(bk_test_x)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [127]:
from sklearn.metrics import confusion_matrix

In [128]:
dec_bk = confusion_matrix(bk_test_y, pred)
dec_bk

array([[36391,  1158],
       [10821,   775]], dtype=int64)

In [129]:
from sklearn.metrics import accuracy_score

In [130]:
accuracy_score(bk_test_y,pred)

0.7562519076203073

In [131]:
from sklearn.tree import DecisionTreeClassifier

In [132]:
dtree = DecisionTreeClassifier(criterion='entropy', max_depth = 5,    min_samples_split=50) #Shift,Tab for init signature

In [133]:
dtree.fit(bk_train_x, bk_train_y)

DecisionTreeClassifier(criterion='entropy', max_depth=5, min_samples_split=50)

In [134]:
dec_pred = dtree.predict(bk_test_x)

In [135]:
dec_pred

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [136]:
dtree_tab = confusion_matrix(bk_test_y, dec_pred)
dtree_tab

array([[37369,   180],
       [10664,   932]], dtype=int64)

In [137]:
accuracy_score(bk_test_y , dec_pred)

0.7793468308067962